server:
  port: 8080

spring:
  application:
    name: mavis-test
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO